"""owner table

Revision ID: 0228b59c8706
Revises: e5f44908fda7
Create Date: 2018-04-16 11:46:13.440000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0228b59c8706'
down_revision = 'e5f44908fda7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('VEHICLE_ID', sa.String(), nullable=True),
    sa.Column('FLEET_OWNER', sa.String(), nullable=True),
    sa.Column('CONTACT_PERSON', sa.String(), nullable=True),
    sa.Column('ADDRESS', sa.String(), nullable=True),
    sa.Column('PHONE_NUMBER', sa.String(), nullable=True),
    sa.Column('EMAIL', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['VEHICLE_ID'], ['vehicle.VEHICLE_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner')
    # ### end Alembic commands ###
