"""Users table

Revision ID: e5f44908fda7
Revises: 
Create Date: 2018-04-16 11:22:01.921000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f44908fda7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('VEHICLE_ID', sa.String(), nullable=True),
    sa.Column('VEHICLE_TYPE', sa.String(), nullable=True),
    sa.Column('CABIN_TYPE', sa.String(), nullable=True),
    sa.Column('MANUFACTURER', sa.String(), nullable=True),
    sa.Column('MODEL', sa.String(), nullable=True),
    sa.Column('MODEL_YEAR', sa.String(), nullable=True),
    sa.Column('VIN', sa.String(), nullable=True),
    sa.Column('GVWR', sa.String(), nullable=True),
    sa.Column('TOTAL_MILES', sa.String(), nullable=True),
    sa.Column('AGENCY_VEHICLE_NUMBER', sa.String(), nullable=True),
    sa.Column('LICENSE_PLATE', sa.String(), nullable=True),
    sa.Column('OEM_COMMENTS', sa.String(), nullable=True),
    sa.Column('AQMD_CATEGORY', sa.String(), nullable=True),
    sa.Column('EMA_CATEGORY', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('VEHICLE_ID', sa.String(), nullable=True),
    sa.Column('MANUFACTURER', sa.String(), nullable=True),
    sa.Column('ENGINE_MODEL', sa.String(), nullable=True),
    sa.Column('ENGINE_YEAR', sa.String(), nullable=True),
    sa.Column('SERIAL', sa.String(), nullable=True),
    sa.Column('EPA_FAMILY_CERT', sa.String(), nullable=True),
    sa.Column('DISPLACEMENT', sa.String(), nullable=True),
    sa.Column('NUMBER_OF_CYLINDERS', sa.String(), nullable=True),
    sa.Column('CONFIGURATION', sa.String(), nullable=True),
    sa.Column('IDLE_SPEED', sa.String(), nullable=True),
    sa.Column('GOVERNED_SPEED', sa.String(), nullable=True),
    sa.Column('HIGH_IDLE', sa.String(), nullable=True),
    sa.Column('REFERENCE_TORQUE', sa.String(), nullable=True),
    sa.Column('ENGINE_REBUILT', sa.String(), nullable=True),
    sa.Column('YEAR_OF_REBUILT', sa.String(), nullable=True),
    sa.Column('ECU_PROTOCOL', sa.String(), nullable=True),
    sa.Column('STOIC_LEAN_BURN', sa.String(), nullable=True),
    sa.Column('PRIMARY_FUEL_TYPE', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['VEHICLE_ID'], ['vehicle.VEHICLE_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transmission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('VEHICLE_ID', sa.String(), nullable=True),
    sa.Column('TOTAL_NO_OF_AXELS', sa.String(), nullable=True),
    sa.Column('NO_OF_DRIVE_AXELS', sa.String(), nullable=True),
    sa.Column('TRANSMISSION_TYPE', sa.String(), nullable=True),
    sa.Column('SPEEDS', sa.String(), nullable=True),
    sa.Column('MANUFACTURER', sa.String(), nullable=True),
    sa.Column('HYBRID_TECH', sa.Boolean(), nullable=True),
    sa.Column('HYBRID_TECH_COMMENTS', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['VEHICLE_ID'], ['vehicle.VEHICLE_ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transmission')
    op.drop_table('engine')
    op.drop_table('vehicle')
    op.drop_table('users')
    # ### end Alembic commands ###
